### ISSUE TITLE
Google Cloud Speech streaming API(sample) doesn't support proxy environment

### ISSUE THREAD

**Issue by chathuranga** [googleapis/nodejs-speech#111]
Does the Google Speech Streaming API(gRPC) support a network with a proxy server? 

We tried this out and didn't work in work in a proxy environment. It'll be really good to document whether this is something not supported or else add steps required to get it working with a proxy server.

https://stackoverflow.com/questions/51250372/error-14-unavailable-connect-failed-with-google-speech-api

We tried this as well, but it didn't work.
https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a

#### Environment details

  - OS: Windows 10
  - Node.js version: v8.11.3
  - npm version: 6.1.0
  - `@google-cloud/speech` version: 1.5.0

**Comment by stephenplusplus** [comment]
Thanks for reporting, and sorry for the delay. I was experimenting, trying to mimic a local proxy. I set the environment variable `https_proxy` and saw different behavior from my Speech API request than when it was not set. It went from connecting to the backend successfully to receiving "Auth error:Error: socket hang up" (which I believe is an expected error, since I don't actually have a proxy server running).

If you're still having this issue, could you list the steps that reproduces the problem?

**Comment by Ravipatel401** [comment]
I Need URL List to Unblock in Firewall for google text to speech API access but I am not sure which URL accessing Google libraries from internal Call. Please let know list so help to just unblock white list from firewall.

**Comment by UmutAlihan** [comment]
> I Need URL List to Unblock in Firewall for google text to speech API access but I am not sure which URL accessing Google libraries from internal Call. Please let know list so help to just unblock white list from firewall.

I also need this information, looking forward for your support

**Comment by chathuranga** [comment]
Hi @Ravipatel401 @UmutAlihan 
As linked above in my comment, below URL list worked for me(this is about 2 years back) 
https://texttospeech.googleapis.com/* 
https://speech.googleapis.com/* 
https://accounts.google.com/*
https://www.googleapis.com/*
https://oauth2.googleapis.com/* 
https://cloud.google.com/*

**Comment by Ravipatel401** [comment]
@chathuranga Thank you for replied but issue solved long before by using some of the URLs you mentioned, Thanks again...
