### ISSUE TITLE
longRunningRecognize to bucket when finished

### ISSUE THREAD

**Issue by jsphweid** [googleapis/nodejs-speech#188]
I created a workflow using google cloud functions and bucket triggers to transcribe an audio file when you put a new item in a certain bucket. Basically a cloud fn calls speech.longRunningRecognize and when the polling is complete, it is saved to another bucket. The problem is that for really really large files (60+ minutes long) it will likely take longer to process than time allowed in a cloud function (max 9 minutes). Therefore the polling part will timeout in the function before it's finished being transcribed and thus lost.

All I want to do is simply save the output of the transcribe job to a bucket when I'm done; I don't really care about operation progress / polling. Although I'm sure I could somehow keep track of the job and periodically fire cloud functions that check the status until the job is done, then handle persisting the result, it's not ideal.

After reading around, it doesn't seem like that's a feature of the API. Is that true? Will this feature be added in the future?

**Comment by stephenplusplus** [comment]
@JustinBeckwith I suspect an answer to this question would come from someone with Cloud Functions experience as well as Speech. This problem seems it could be common enough that a solution has already been found. Have you heard of an ideal practice for performing long-running tasks inside of a Cloud Function?

**Comment by JustinBeckwith** [comment]
@ace-n and @beccasaurus may have thoughts here :)

**Comment by ace-n** [comment]
(On my phone, so excuse the murky answer.)

The right way to do this depends on whether or not you can get a
notification (Pub/Sub, HTTP, *Stackdriver Log*, or otherwise) once the
transcription job completes.

If you *can*, then you can forward that notification to a Cloud Function.

If you *cannot*, then you'll (somehow) have to poll manually. A couple
things you might try:
- have functions (recursively) kick off instances of themselves to continue
polling
- use Pub/Sub as a polling queue with a long ack deadline. (Publish a
message after starting the job, and don't ack() it until the job is
complete or has failed. The message will be resent - and trigger your
polling function - periodically until it is ack()'ed.)

From what I know, there are no direct notifications from the Speech
Transcription API - so Stackdriver log forwarding is probably your best bet
*if* job completion is logged in Stackdriver. Failing that, you'd want to
implement some sort of manual polling solution.

Hope this helps!
