### ISSUE TITLE
Authenticating via API key not supported?

### ISSUE THREAD

**Issue by alecglassford** [googleapis/nodejs-speech#19]
Hello!

It seems that authenticating with an API key is not supported in this client. But while the docs for nodejs-speech don't mention it as an option, the [general google-cloud-node docs on authentication](https://github.com/GoogleCloudPlatform/google-cloud-node#elsewhere) suggest you can authenticate with an API key for "any APIs that accept an API key." Following the pattern of passing a `key` attribute to the constructor (I tried with both `@google-cloud/speech` and the meta `google-cloud` package) gives `Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.`

Are there any plans to make this possible for the speech client? Otherwise, perhaps that language should be adjusted.

Thanks!

#### Environment details

  - OS: macOS 10.13.3
  - Node.js version: 9.4.0
  - npm version: 5.6.0
  - @google-cloud/speech version: 1.0.1

#### Steps to reproduce

  1. Create project, enable Google Speech API, generate API key with no restrictions.
  2. Run code like
```
import speech from '@google-cloud/speech';
const sc = new speech.v1.SpeechClient({
  projectId: process.env.GCLOUD_PROJECT_ID,
  key: process.env.GCLOUD_API_KEY,
});
sc.getProjectId((err, str) => {
  console.log(err);
});
```

**Comment by stephenplusplus** [comment]
Thanks for pointing this out and sorry for the confusion.

@alexander-fenster what do we think about API key authentication?

**Comment by alexander-fenster** [comment]
I agree that the docs are confusing, we'll work on it.
As for API KEY authentication, it's definitely supported. Our system test uses it (please see below): https://github.com/googleapis/nodejs-speech/blob/b58de64badbc077f28731a40604e780328d7d660/.circleci/config.yml#L204
Can you try putting the full path to your key JSON file into `GOOGLE_APPLICATION_CREDENTIALS` environment variable? Then you don't need to pass it to the constructor.

If it works for you, we'll work on updating the documentation to reflect the correct usage.

**Comment by stephenplusplus** [comment]
This is actually in regards to an API key, like these: https://cloud.google.com/docs/authentication/api-keys

**Comment by alexander-fenster** [comment]
Ah. Sorry then, let me take a look once more.

**Comment by phsultan** [comment]
Hello,

I don't think it's possible at the moment since `google-auto-auth` which is used internally in `node_modules/\@google-cloud/speech/node_modules/google-gax/lib/grpc.js` does not seem to support that option.

There is an issue that references this as a request after the option has been added to the underlying `google-auth-library-nodejs` : https://github.com/stephenplusplus/google-auto-auth/issues/9

I tried the following without success : 
```
var googleAuth = require('google-auto-auth');
const speech = require('@google-cloud/speech');
const fs = require('fs');

var gAuthClient = googleAuth({
  apiKey: 'MY_API_KEY'
})

const client = new speech.SpeechClient({
  projectId: "MY_PROJECT_ID',
  auth: gAuthClient
});
```

Could be my environment though : 
- Node.js : 9.5.0
- npm : 5.6.0
- `@google-cloud/speech` : 1.2.0

**Comment by E3V3A** [comment]
@phsultan What was the error you received?

**Comment by phsultan** [comment]
I just received an 'Invalid grant' message from the API server, and actually, nothing in the code of `google-auto-auth` would allow me to authenticate using `apiKey` as an attribute.

@stephenplusplus, is it something that is planned to be included in `google-auto-auth` ? If so, would you accept PRs in that regard ?

I'm asking because of these two issues:
- https://github.com/stephenplusplus/google-auto-auth/issues/9 (attempt to authenticate using `apiKey`, now closed)
- https://github.com/stephenplusplus/google-auto-auth/issues/39 (deprecation message)

**Comment by stephenplusplus** [comment]
We've had an API or two that used API keys for authentication in the past, and google-auto-auth wasn't involved at all, actually. For example, in the case of Speech, we would accept it as an argument:

```js
const speech = new Speech({ apiKey: '...' })
```

Then we'd give the key right to gRPC to use however it does.

However, a PR to accept a key in google-auto-auth probably wouldn't hurt, so I'd definitely take it :)

**Comment by phsultan** [comment]
I can give a bit more feedback on this issue. From my testing, I was not able to pass the API key to gRPC in all cases. However, using `google-auth-library` or even `axios` directly to send REST requests is pretty straightforward, and mostly preserves the code patterns we have with `@google-cloud/speech`:
- [gist using google-auth-library](https://gist.github.com/phsultan/60b7b33270be54453252b759f141eabc)
- [gist using axios](https://gist.github.com/phsultan/794c41f1d540611821f34ab070d41bdf)

I tried to pass the API key as a `key` parameter to gRPC by adding it as a metadata or as a request attribute and after having modified the `cloud_speech.proto` file with no luck. The reason why I modified `cloud_speech.proto` was to try to pass the `key` as a URL parameter, but I'm not even sure that's the right way to go.

Here is the corresponding code : [gist using gRPC](https://gist.github.com/phsultan/3b38a508072d83e374cbbbcf13485f1c)

Hope this helps!

**Comment by martinraison** [comment]
I'd be fine with using a service account as recommended in the documentation, however the real issue is that there doesn't seem to be any predefined Role for granting API access to service accounts. The only way for a service account to access the Speech-To-Text API is to give it the "Owner" role, which is a non-starter for most real-world use-cases.

Any chance we can have a more granular permission system in the future ? In the meantime, being able to use an API key would solve the issue, since API keys can be restricted to a specific API (e.g. Speech-To-Text).

**Comment by DevJhns** [comment]
> 
> 
> We've had an API or two that used API keys for authentication in the past, and google-auto-auth wasn't involved at all, actually. For example, in the case of Speech, we would accept it as an argument:
> 
> ```js
> const speech = new Speech({ apiKey: '...' })
> ```
> 
> Then we'd give the key right to gRPC to use however it does.
> 
> However, a PR to accept a key in google-auto-auth probably wouldn't hurt, so I'd definitely take it :)

Man, does this mean, that if I get/create api key for speech-to-text, I can create two speech clients, that can create two speech-to-text streams at same time?

**Comment by alexander-fenster** [comment]
Hi folks,

I'm just going to update this issue to let you all know that it is possible to authenticate Node.js Speech client using an API key, even though it's a little bit hacky. This [gist](https://gist.github.com/alexander-fenster/9e963e425dc25392246896731e9c88be) shows the complete example, the main idea is here:

```js
const apiKey = 'REDACTED'; // <-- use your API key here
const speech = require('@google-cloud/speech');
const {GoogleAuth, grpc} = require('google-gax');

function getApiKeyCredentials() {
  const sslCreds = grpc.credentials.createSsl();
  const googleAuth = new GoogleAuth();
  const authClient = googleAuth.fromAPIKey(apiKey);
  const credentials = grpc.credentials.combineChannelCredentials(
    sslCreds,
    grpc.credentials.createFromGoogleCredential(authClient)
  );
  return credentials;
}

const sslCreds = getApiKeyCredentials();
const client = new speech.SpeechClient({sslCreds});
```

Anyway, please be advised that we recommend using service account key for authentication on the server side, and OAuth2 for the client side authentication. Please consider using either of those instead of API key authentication.
