### ISSUE TITLE
Simplify examples in documentation

### ISSUE THREAD

**Issue by phsultan** [googleapis/nodejs-speech#46]
Hi,

Some examples (two actually) in the repository still make use of the unnecessary `projectId` argument when instantiating a `SpeechClient`, which can somehow be a bit confusing when starting to use the client.

I'm issuing a PR to propose a fix that instantiates `SpeechClient` without any argument, thus following the examples in `samples/recognize.js` and `samples/recognize.v1p1beta1.js`.

Also, the page at the URL `https://cloud.google.com/nodejs/docs/reference/speech/latest/` (linked in `README.md`) should be updated : 
- should point to https://cloud.google.com/nodejs/docs/reference/speech/1.2.x (latest version)
- the corresponding page still uses `projectId`

Thanks a lot for this great program, we're loving it !

**Comment by stephenplusplus** [comment]
I'm glad to hear it's working well, and thanks for taking the time to help!

@alexander-fenster what do you think about removing the project ID from the examples? Without looking, I'm pretty sure our other APIs show this option. However, maybe it really isn't that vital anymore, since a project ID can be detected in all GCP environments as well as from a JSON service account key file. I suppose the only times it can't be are when:

- A user provides `credentials` object, without a project ID
- A user provides a PEM/P12 key file

@jmdobry 1.2.0 was released 3 days ago. I assume there is just some lag in when the docs site gets updated?

**Comment by alexander-fenster** [comment]
I'm OK - I approved #47. We'll see if samples tests work after this change is merged (I guess they should).
