### ISSUE TITLE
Incorrect time being reported for billing

### ISSUE THREAD

**Issue by matrix4123** [googleapis/nodejs-speech#528]
Not sure who to ask about this... but I've reached out to support and didn't get anywhere. 

I am using the beta API and uploading MP3 files to the longrunningrecognize method. The billing we are seeing is about 3 to 4 times the length of the audio files that we are uploading. This is getting very costly and quickly! The only thing I can think of is that the files are MP3 and this is still in beta API only?

Not sure how else to debug this on my end... I've taken a single day and added up all the files by length and then compared to the billing portal and it doesn't come close.

Any ideas?

**Comment by bcoe** [comment]
@matrix4123 thanks for the bug report, I'll make an effort to share your feedback internally.

**Comment by nnegrey** [comment]
Howdy, asking around, but one question: how many audio channels are there?

**Comment by matrix4123** [comment]
> Howdy, asking around, but one question: how many audio channels are there?

Codec: MPEG Audio layer 1/2 (mpga)
Type: Audio
Channels: Mono
Sample rate: 11025 Hz
Bits per sample: 32
Bitrate: 64 kb/s

These are VOIP phone calls recorded to mp3. Here is the config I am using, maybe the sample rate is messing it up?

```javascript
const config = {
  encoding: "MP3",
  sampleRateHertz: 16000,
  languageCode: "en-US",
  model: 'phone_call',
  useEnhanced: true,
  diarizationConfig: {
    enableSpeakerDiarization: true
  },
  metadata: {
    interactionType: "PHONE_CALL",
    originalMediaType: "AUDIO",

  }
```

**Comment by nnegrey** [comment]
@matrix4123, would you mind filing an issue on this page for speech-to-text?
https://cloud.google.com/support/docs/issue-trackers

**Comment by nnegrey** [comment]
or if you don't mind sharing your projectId or number here, I can pass that along to the product team to take a look.

**Comment by noseratio** [comment]
Hi @matrix4123, if I may ask you, do you find the quality of the diarized results acceptable? 

It is so low to me that I was thinking it must a bug in my code (which otherwise works great for one speaker per channel). Then I've found other people are complaining about [the multi-speakers feature](https://stackoverflow.com/q/62883413/1768303) as well. 

I use `Speech.v1p1beta1` and I realize it's still a beta-quality services, but it really feels like alpha so far. I wonder is there is any roadmap for it, maybe @nnegrey could shed some light.

Thanks for any thoughts.

**Comment by b-loved-dreamer** [comment]
This issue was inactive for longer than a year and it may no longer be relevant. I am closing this issue now but feel free to reopen if you still are experiencing issues.
