### ISSUE TITLE
STDERR: ALSA lib confmisc.c:767:(parse_card) cannot find card '0'

### ISSUE THREAD

**Issue by rithiksachdev** [googleapis/nodejs-speech#589]
`record  sox --default-device --no-show-progress --rate 16000 --channels 1 --encoding signed-integer --bits 16 --type wav - +3ms
Listening, press Ctrl+C to stop.
  record STDERR: ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
  record ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
  record ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
  record ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
  record ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
  record ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
  record ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
  record ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
  record sox FAIL formats: can't open input  default: snd_pcm_open error: No such file or directory
  record  +24ms
  record Recording ended +14ms
sox has exited with error code 2.
Enable debugging with the environment variable DEBUG=record.`

`/cloudshell_open/nodejs-speech-0/samples$ echo $DEBUG`

`record`

**Comment by stephenplusplus** [comment]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-speech/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/speech` version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by rithiksachdev** [comment]
Thanks, @stephenplusplus, It was a repeated question on StackOverflow. Thanks for your response again.
