### ISSUE TITLE
Infinite Streaming Interm Transcript Never Sent with "isFinal" Flag is Dropped After Stream Restart

### ISSUE THREAD

**Issue by NickDario** [googleapis/nodejs-speech#692]
Hello, 
First thanks for the node client, it's a real boon to us operating in a nodejs ecosystem. Our issues are around the infinite stream sample which navigates the 5 minute time limit.

We are finding an inconsistent behavior after the stream restarts. The interm results contain the full transcript that grows until the "isFinal":true is passed at which point the transcript resets. Stream restarts normally have no effect on this behavior. 
However occasionally the transcript will reset after the stream restarts without "isFinal":true having been sent. This leaves us absent of any signal confirming the previous transcript and is of particular trouble for us as we are discretizing and sending chunks of interm results and having the transcript change throws off the offsets we use to determine what text is sent. 

Below is a distillation of what we are observing. the stream restart _should_ have no effect on the transcript however we are observing the transcript reset (though often not to an empty transcript) after the stream restarts, and without ever sending "isFinal":true. (as represented on lines 17 & 18)

```
// startStream
0: {transcript : "", isFinal:false}
1: {transcript : "This is", isFinal:false}
2: {transcript : "This is a test", isFinal:false}
// restartStream
3: {transcript : "This is a test a", isFinal:false}
4: {transcript : "This is a test, a streaming test", isFinal:false}
5: {transcript : "This is a test, a streaming test.", isFinal:true}

6: {transcript : "this is another", isFinal:false}
7: {transcript : "this is another test", isFinal:false}
8: {transcript : "this is another test", isFinal:false}
// restartStream
9: {transcript : "this is another test that works", isFinal:false}
10: {transcript : "this is another test that works fine", isFinal:false}
11: {transcript : "this is another test that works fine.", isFinal:true}

// restartStream
12: {transcript : "now", isFinal:false}
13: {transcript : "now you ill", isFinal:false}
14: {transcript : "now", isFinal:false}
// restartStream
15: {transcript : "now you will", isFinal:false}
16: {transcript : "now you will see", isFinal:false}
17: {transcript : "now you will see the problem", isFinal:false}

// restartStream
18: {transcript : "There was no", isFinal:false}
19: {transcript : "There was no is final", isFinal:false}
20: {transcript : "There was no is final sent", isFinal:false}
// restartStream
21: {transcript : "There was no is final sent for the prior", isFinal:false}
22: {transcript : "There was no is final sent for the prior transcript", isFinal:false}
23: {transcript : "There was no is final sent for the prior transcript.", isFinal:true}


```

We are observing this using the infinite streaming sample but not using the long running recognizer.
The specs we're testing with are:
  - OS: Ubuntu 18.04.1
  - Node.js version: v14.15.1
  - npm version: 6.14.8
  - `@google-cloud/speech` version: 4.2.0

Please let me know if you are familiar with this behavior, we can put together more precise repro steps if needed.

**Comment by b-loved-dreamer** [comment]
Hi @NickDario, I will inquire about this with the relevant parties.

**Comment by b-loved-dreamer** [comment]
Hi @NickDario , after carefully observing for the behavior you described, I could not replicate your experience with the ```isFinal``` flag on re-starting the stream after the 5 minutes time limit. 

You could ```const streamingLimit = 10000; // ms - set to low number for testing purposes```

This is the expected behavior:

> Before the streaming time limit is met, the program uses the
 'result end time' parameter to calculate the last 'isFinal' transcription.
  When the time limit is met, the unfinalized audio from the previous session
  is resent all at once to the API, before continuing the real-time stream
  and resetting the clock, so the process can repeat.
 Incoming audio should not be dropped / lost during reset, and context from
  previous sessions should be maintained as long the utterance returns an
  isFinal response before 2 * streamingLimit has expired.

This being an interment behavior makes a bit more difficult to reproduce. So, if you can provide more precise repro steps, as you offered, that'd be great. 

A peek at what I observed:

<img width="892" alt="Screen Shot 2021-02-18 at 1 10 38 PM" src="https://user-images.githubusercontent.com/69214580/108424535-28776300-71ee-11eb-9788-e9b1a1b3f196.png">

**Comment by b-loved-dreamer** [comment]
Closing this issue. Please reopen if needed.
